156: Fixed cross-container IMPORT with Exasol 7.1
exasol/exasol-testcontainers pull request #184
Opened 2022-02-14 11:52 UTC by redcatbear

Closes #156.

2022-02-14 12:33 UTC, kaklakariada requested changes

2022-02-14 12:33 UTC, kaklakariada commented on doc/changes/changes_6.1.0.md
> +Cross-container `IMPORT` now also works with version 7.1 thanks when using the TLS fingerprint in the `EXA` connection.
```suggestion
Cross-container `IMPORT` now also works with version 7.1 when using the TLS fingerprint in the `EXA` connection.
```
❓

2022-02-14 12:35 UTC, kaklakariada approved these changes

2022-02-15 11:54 UTC, pj-spoelders approved these changes
Looks good!

2022-02-15 11:54 UTC, merged